
export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAILURE = "DELETE_EXPENSE_FAILURE";

export const EDIT_EXPENSE_REQUEST = "EDIT_EXPENSE_REQUEST";
export const EDIT_EXPENSE_SUCCESS = "EDIT_EXPENSE_SUCCESS";
export const EDIT_EXPENSE_FAILURE = "EDIT_EXPENSE_FAILURE";

export const FETCH_EXPENSE_REQUEST = "FETCH_EXPENSE_REQUEST";
export const FETCH_EXPENSE_SUCCESS = "FETCH_EXPENSE_SUCCESS";
export const FETCH_EXPENSE_FAILURE = "FETCH_EXPENSE_FAILURE";

export const SORT_EXPENSES_BY_CATEGORY = "SORT_EXPENSES_BY_CATEGORY";
export const FILTERED_BY_MONTH = "FILTERED_BY_MONTH";
export const SET_LOADING = "SET_LOADING";

export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const SET_SEARCH_LIST = "SET_SEARCH_LIST";


