export const FETCH_EXPENSE_GRAPH_REQUEST = "FETCH_EXPENSE_GRAPH_REQUEST";
export const FETCH_EXPENSE_GRAPH_SUCCESS = "FETCH_EXPENSE_GRAPH_SUCCESS";
export const FETCH_EXPENSE_GRAPH_FAILURE = "FETCH_EXPENSE_GRAPH_FAILURE";