export default {
  loyaltyCap: {
    currentOrgDetails: {},
    user: {},
    sidebarMenuData: [],
    topbarMenuData: [],
    fetchingUserdata: false,
    getLastSyncTimeStatus: '',
    lastSyncTime: '',
    getOrgKpiConfigStatus: '',
    orgKpiConfig: [],
    getProgramFilterTypeStatus: '',
    programFilterType: {},
    lastSyncTimeError: null,
    orgKpiConfigError: null,
    programFilterTypeError: null,
    getFieldDataStatus: '',
    allContributors: [],
    entities: {},
    getFieldDataError: null,
    getMappedEntitiesStatus: '',
    mappedEntities: {},
    mappedEntitiesError: null,
  },
};
