export const FETCH_USER_BORROWED_BOOKS = 'FETCH_USER_BORROWED_BOOKS';
export const FETCH_USER_BORROWED_BOOKS_SUCCESS =
  'FETCH_USER_BORROWED_BOOKS_SUCCESS';
export const FETCH_USER_BORROWED_BOOKS_FAILURE =
  'FETCH_USER_BORROWED_BOOKS_FAILURE';

export const RETURN_USER_BORROWED_BOOKS = 'RETURN_USER_BORROWED_BOOKS';
export const RETURN_USER_BORROWED_BOOKS_SUCCESS =
  'RETURN_USER_BORROWED_BOOKS_SUCCESS';
export const RETURN_USER_BORROWED_BOOKS_FAILURE =
  'RETURN_USER_BORROWED_BOOKS_FAILURE';
