export const FETCH_ALL_BOOKLIST = 'booklist/FETCH_ALL_BOOKLIST';
export const FETCH_ALL_BOOKLIST_SUCCESS = 'booklist/FETCH_ALL_BOOKLIST_SUCCESS';
export const FETCH_ALL_BOOKLIST_FAILED = 'booklist/FETCH_ALL_BOOKLIST_FAILED';
