export const FETCH_ALL_BOOK_REQUESTS_REQUEST =
  'FETCH_ALL_BOOK_REQUESTS_REQUEST';
export const FETCH_ALL_BOOK_REQUESTS_SUCCESS =
  'FETCH_ALL_BOOK_REQUESTS_SUCCESS';
export const FETCH_ALL_BOOK_REQUESTS_FAILURE =
  'FETCH_ALL_BOOK_REQUESTS_FAILURE';

export const ADD_NEW_BOOK_REQUEST_REQUEST = 'ADD_NEW_BOOK_REQUEST_REQUEST';
export const ADD_NEW_BOOK_REQUEST_SUCCESS = 'ADD_NEW_BOOK_REQUEST_SUCCESS';
export const ADD_NEW_BOOK_REQUEST_FAILURE = 'ADD_NEW_BOOK_REQUEST_FAILURE';
export const REMOVE_ERROR = 'REMOVE_ERROR';
