export const newBookRequests = [
  {
    request_id: '1',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '2',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '3',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '4',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '5',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '6',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '7',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '8',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '9',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '10',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '11',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '12',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '13',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '14',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '15',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '16',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '17',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '18',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '19',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
  {
    request_id: '20',
    email: 'admin@example.com',
    date: '2024-02-15',
    book_name: 'Pride and Prejudice',
    book_author: 'Jane Austen',
  },
];
