export const LIB_SIGNUP_REQUEST = 'LIB_SIGNUP_REQUEST';
export const LIB_SIGNUP_SUCCESS = 'LIB_SIGNUP_SUCCESS';
export const LIB_SIGNUP_FAILURE = 'LIB_SIGNUP_FAILURE';

export const LIB_SIGNIN_REQUEST = 'LIB_SIGNIN_REQUEST';
export const LIB_SIGNIN_SUCCESS = 'LIB_SIGNIN_SUCCESS';
export const LIB_SIGNIN_FAILURE = 'LIB_SIGNIN_FAILURE';
