export const FETCH_USER_REQUESTED_BOOKS = 'FETCH_USER_REQUESTED_BOOKS';
export const FETCH_USER_REQUESTED_BOOKS_SUCCESS =
  'FETCH_USER_REQUESTED_BOOKS_SUCCESS';
export const FETCH_USER_REQUESTED_BOOKS_FAILURE =
  'FETCH_USER_REQUESTED_BOOKS_FAILURE';
export const CANCEL_USER_REQUESTED_BOOKS = 'CANCEL_USER_REQUESTED_BOOKS';
export const CANCEL_USER_REQUESTED_BOOKS_SUCCESS =
  'CANCEL_USER_REQUESTED_BOOKS_SUCCESS';
export const CANCEL_USER_REQUESTED_BOOKS_FAILURE =
  'CANCEL_USER_REQUESTED_BOOKS_FAILURE';
